
# html lang
language: ko

# header
site_brand_name: Robin The Dev

logo_image:
  enable: false
  image_path: /logo.png # path to your logo image

menu:
  All articles: /articles/
#  Ruby And Rails: /categories/rails

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/menu.js

# favicon
favicon: /favicon.ico

date_format: YYYY-MM-DD

# footer
footer:
  copyright_info:
    enable: true
    author: Robin Seo

  other_info:
    enable: true
    content: Rubyist, Amateur Song Writer

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false

valine:
  enable: false

disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'en'

# local search
local_search:
  enable: true
  place_holder: Search Anything
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: 1 # show top n results per article, show all results by setting to -1
  unescape: false # unescape html strings to the readable one
  preload: false # reload the search data when the page loads, this will accelerate the search process
